apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qcs7tdxqm-nodejs
  janus-idp.io/tekton: qcs7tdxqm-nodejs
  backstage.io/kubernetes-id: qcs7tdxqm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qcs7tdxqm-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
